platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

project 'Shekly'

def utilities
  pod 'SwiftyBeaver', '1.8.2'
  pod 'R.swift', '5.0.3'

  pod 'SwiftDate', '6.1.0'
  pod 'DynamicColor', '4.2.0'
  pod 'SwiftLint', '0.35.0'
  pod 'Dip', '7.0.1'
end

target 'Shekly' do
  utilities
end

target 'Shared' do
  utilities
end

target 'UI' do
  utilities
end

target 'Domain' do
  utilities
end

target 'DomainTests' do
  utilities
end

target 'User' do
  utilities
end

target 'SHTokenField' do
  utilities
end

target 'Database' do
  utilities
end
