project 'Shekly-generated'
platform :ios, '13.0.0'
use_frameworks!

def static_pods
  pod 'RealmSwift', '4.4.1'
end

target 'Shekly' do 
  static_pods
end

target 'Database' do
  static_pods
end

target 'Vendors' do
end
