platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

project 'Shekly'

def rx
  pod 'RxSwift', '4.3.1'
  pod 'RxCocoa', '4.3.1'
  pod 'RxOptional', '3.5.0'
  pod 'RxDataSources', '3.1.0'

  pod 'RxMVVMC', :git => 'https://bitbucket.org/PatrykMieszala/RxMVVMC', :tag => '1.0.0'
end

def networking
  pod 'Alamofire', '4.7.3'
end

def utilities
  pod 'R.swift', '5.0.2'

  pod 'Charts', '3.2.1'
  pod 'SwiftDate', '6.0.1'
  pod 'DynamicColor', '4.0.2'
end

target 'Shekly' do
  rx
  networking
  utilities
end

target 'Shared' do
  rx
  networking
  utilities
end

target 'UI' do
  rx
  networking
  utilities
end

target 'Domain' do
  rx
  networking
  utilities
end

target 'User' do
  rx
  networking
  utilities
end

target 'SHTokenField' do
    rx
    networking
    utilities
end

target 'Database' do
    rx
    networking
    utilities
end
