name: Shekly-generated

packages:
  Rswift:
    url: https://github.com/mac-cain13/R.swift.Library
    exactVersion: 5.2.0
  SwiftyBeaver:
    url: https://github.com/SwiftyBeaver/SwiftyBeaver
    exactVersion: 1.8.2
  SwiftDate:
    url: https://github.com/malcommac/SwiftDate
    exactVersion: 6.1.0
  DynamicColor:
    url: https://github.com/yannickl/DynamicColor
    exactVersion: 5.0.0
  Dip:
    url: https://github.com/AliSoftware/Dip
    exactVersion: 7.1.1

options:
  bundleIdPrefix: pl.swiftoletzbrothers
  minimumXcodeGenVersion: 2.13.1
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget: 
    iOS: "13.0"
  xcodeVersion: 11.3
  preGenCommand: sh check-generated-files.sh

configs:
  Debug: debug
  Release: release

schemes:
  Shekly:
    build:
      targets:
        Shekly: all

targets:
  Shekly:
    type: application
    platform: iOS
    attributes:
      DevelopmentTeam: SATYASXVS5
      ProvisioningStyle: Manual
    settings:
      base:
        INFOPLIST_FILE: Shekly/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: pl.swiftoletzbrothers.shekly
    sources: 
      - Shekly
    dependencies:
      - target: Vendors
      - target: AppRoutes
      - target: Common
      - target: Domain
      - target: Database
      - target: User
      - target: SHTokenField
      - target: CleanArchitectureHelpers
      - target: CommonUI
      - target: Main
      - target: Tabs
      - target: NewEntry
      - target: Wallet
      - target: Plan
    preBuildScripts:
      - script: 'mint run mac-cain13/R.swift@v5.2.0 rswift generate "$SRCROOT/Shekly/Generated/R.generated.swift"'
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/Shekly/Generated/R.generated.swift
    postCompileScripts:
      - script: mint run realm/SwiftLint@0.39.1 swiftlint
        name: Swiftlint

  SheklyShare:
    type: app-extension
    platform: iOS
    sources: SheklyShare
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: pl.swiftoletzbrothers.shekly.sheklyShare
    entitlements:
      path: SheklyShare/SheklyShare.entitlements
      properties:
        com.apple.security.application-groups: [group.pl.swiftoletzbrothers.shekly]
    dependencies:
      - package: Dip
      - target: Database

  Vendors:
    type: framework
    platform: iOS
    dependencies:
      - package: Rswift
      - package: SwiftDate
      - package: DynamicColor
      - package: Dip
      - package: SwiftyBeaver
    configVariants:
      - Debug
      - Release
    sources:
      - Vendors

  AppRoutes:
    templates: 
      - Framework

  CleanArchitectureHelpers:
    templates: 
      - Framework
    dependencies:
      - target: Common

  Common:
    templates: 
      - Framework
    dependencies:
      - target: Domain

  Main:
    templates: 
      - Framework
    dependencies:
      - target: Domain
      - target: Common
      - target: CommonUI
      - target: CleanArchitectureHelpers
      - target: AppRoutes

  Tabs:
    templates: 
      - Framework
    dependencies:
      - target: Domain
      - target: Common
      - target: CommonUI
      - target: CleanArchitectureHelpers
      - target: AppRoutes

  NewEntry:
    templates: 
      - Framework
    dependencies:
      - target: Domain
      - target: CleanArchitectureHelpers
      - target: Common
      - target: CommonUI

  Wallet:
    templates: 
      - Framework
    dependencies:
      - target: Domain
      - target: CleanArchitectureHelpers
      - target: Common
      - target: CommonUI

  Plan:
    templates: 
      - Framework
    dependencies:
      - target: Domain
      - target: CleanArchitectureHelpers
      - target: Common
      - target: CommonUI

  Domain:
    templates: 
      - Framework

  Database:
    templates: 
      - Framework
    dependencies:
      - target: Common
      - target: Domain

  User:
    templates: 
      - Framework
    dependencies:
      - target: Common

  SHTokenField:
    templates: 
      - Framework
    dependencies:
      - target: Common

  CommonUI:
    type: framework
    platform: iOS
    dependencies:
      - target: Vendors
      - target: Domain
      - target: CleanArchitectureHelpers
    configVariants:
      - Debug
      - Release
    sources:
      - CommonUI
      - path: CommonUI/Generated
        optional: true
    preBuildScripts:
      - script: 'mint run mac-cain13/R.swift@v5.2.0 rswift generate --accessLevel public "$SRCROOT/CommonUI/Generated/R.generated.swift"'
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/CommonUI/Generated/R.generated.swift

targetTemplates:
  Framework:
    type: framework
    platform: iOS
    dependencies:
      - target: Vendors
    configVariants:
      - Debug
      - Release
    sources:
      - ${target_name}
      - path: ${target_name}/Generated
        optional: true
    preBuildScripts:
      - script: 'mint run mac-cain13/R.swift@v5.2.0 rswift generate "$SRCROOT/${target_name}/Generated/R.generated.swift"'
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/${target_name}/Generated/R.generated.swift
